### PR TITLE
Add bytes attachments

### PR DESCRIPTION
**Pull request by PawelStroinski**
It is handy to be able to use a byte array rather than a file as the attachment `:content`. Test included.

### CODE REVIEW

**Comment by whamtet** [comment]
Can @drewr please merge this?

**Comment by lmccombes** [comment]
Thanks @PawelStroinski, I've made use of this branch as I needed this feature. If we could get it merged onto the main project that would be great!

**Review by drewr — APPROVED** [review]
This is great! Sorry for the long delay @PawelStroinski and thank you for the patch. Also thanks @lmccombes and @whamtet for the escalation. ❤️

**Comment by whamtet** [comment]
Great work @drewr !

**Comment by lmccombes** [comment]
Thanks @drewr , much appreciated!

**Comment by PawelStroinski** [comment]
Thank you @drewr for merging this and making `postal` in the first place! Thank you @whamtet, @lmccombes and @rafaeldelboni for finding this PR useful!

**Comment by rafaeldelboni** [comment]
Thanks a lot @PawelStroinski and @drewr cc @lucasdf

**Pull request merged**
