### PR TITLE
simpler logic for determining from, to, and bcc

### PR DESCRIPTION
**Pull request by bostonaholic**

### CODE REVIEW

**Comment by bostonaholic** [comment]
@drewr Any plans to merge or close this?

**Comment by bostonaholic** [comment]
ping @drewr

**Comment by bostonaholic** [comment]
Cleaning up my stale PRs and forks. Feel free to reopen and merge if you feel the changes are still needed.

**Comment by drewr** [comment]
Sorry never merging it @bostonaholic. I'll just roll into some other changes. Trying to get more regular on the maintenance!

**Pull request closed without merging**
